### ISSUE TITLE
Add down action to TetrisAfterStateGenerator

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#100]
I don't think that adding the down action will hurt how after states are generated, and hopefully this will lead to agents that clear more lines within the evaluation time limit since they can just drop the piece into place as quickly as possible. I think that the down action should be first in the sequence of actions to try, but some experimentation will be needed to see what actually works best.

However, there is one thing to watch out for: make sure that allowing the down action does not prevent the agent from doing sequences of actions that involve letting a piece drop to be touching the bottom, but then you scoot it in one square to the left or right to fill in a gap. You should add specific unit tests for this case to make sure the player can still do these actions.

**Comment by Serenamidori** [comment]
Currently, we've added the Fall action to the order of actions in the generator, and it works in making some action lists shorter, and does not interfere with some special cases. (JUnit tests done)

Since this all works now, I'm going to close this and move onto #102 to make sure we can actually take these now-shorter paths.
