### ISSUE TITLE
Save best agents for each generation for PredPrey cooperative coevolution

### ISSUE THREAD

**Issue by Rollinsa** [schrum2/MM-NEATv2#146]
Implement an operation which will save the highest scoring agent for each population of each generation. This will be used by the coevolution best objective watch.

**Comment by Rollinsa** [comment]
#19 #142

**Comment by schrum2** [comment]
You need to copy functionality in LonerTask over to similar functionality in CooperativeTask.

In LonerTask, make sure you avoid the code that is specific for Ms Pac-Man ... you want to make general code that works for multiple objectives. For the LonerTask, the best individual in each objective gets saved. Lines 243-254 of the LonerTask track the best score for each objective. The CooperativeTask needs to do this for each objective and each population. In the LonerTask, lines 279-297 actually save the best individual in each objective to an xml file in the bestObjectives subdirectory. In the CooperativeTask, you should save the best individuals in each population to directories pop0_bestObjectives, pop1_bestObjectives, etc.

**Comment by Rollinsa** [comment]
Attempted to implement the saving of the best agent in each objective in each population in torusPredPrey cooperative coevolution. I was able to implement all of the code (and I think it will work correctly) except for the small but essential part of getting the score of each agent, and because I was unable to do this the rest of the code that I just added needed to be commented out as well for now. The added code was in CooperativeTask.

**Comment by schrum2** [comment]
You do not need a  saveBestForEachPopulation method. You should actually
remove this. Instead, some of the code for this needs to appear in
the evaluateAllPopulations method.

Within the for (int i = 0; i < totalEvals; i++) loop, you need to track the
best score in each objective for each sub-population. The actual scores are
already available, because the evaluate method is already being called.

Then, after the loop, you can save the best individuals to xml files, if
(CommonConstants.netio).

**Comment by Rollinsa** [comment]
Finished implementing the saving of the best agent of each objective in each population for the cooperative coevolution task. Seems to work correctly when tested with torusPredPrey coevolution task (the task ran without errors, and created the new directories, one for each population, with the best agents).
