### ISSUE TITLE
More VizDoom Tasks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#148]
It should be fairly straight-forward to create vizdoom tasks for each of the scenario wad and cfg files in the vizdoom subdirectories. I don't even know what all of these are, but go ahead and make a task for each. You can set up the actions based on the CFG file contents. Don't worry about the reward functions too much ... we'll get into those in detail later. Just get the tasks running first. Once they are running, you can strive to make the reward functions accurate.

**Comment by Serenamidori** [comment]
All of the config files have corresponding task files now, with the exception of bots.cfg since it's not a game config, and that HealthGatherTask has two available wad files but I did not make two different tasks as the second isn't listen in the config. They all run, but they may have a mistake here or there (time steps or combinations of action buttons)
