### ISSUE TITLE
Add lineage trace function to picbreeder

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#151]
Find a way to turn on log functions for picbreeder task so lineages can be remembered and potentially drawn #149

**Comment by schrum2** [comment]
You should be able to use the existing linear browser if you add code to track all lineage data. However, currently you are not even advancing the generation. A lot of code needs to be added to getNextGeneration, but much of it will be similar to code that exists elsewhere. Here are some guidelines.

generation++ needs to happen.

You need a method like the logParentInfo method from MuLambda (but don't do any modeLogging). Note that in MuLambda, there is separate logging of "parent" and "child" populations ... these do not exist in the selective breeding EA. At any given point, there is only one population.

Make the following two calls at the appropriate place:
EvolutionaryHistory.logMutationData("---Gen " + generation + " Over-----------------");
EvolutionaryHistory.logLineageData("---Gen " + generation + " Over-----------------");

Close any logs you need to close in your EA's close method.

You will also need to make some changes to the PicbreederTask. Because Picbreeder task is not an instance of LonerTask, you will need to import some of the useful code from there. In fact, it might make sense to define a PopulationTask, but I'll make another issue for that. Here is the code you need from LonerTask:

There is an if (CommonConstants.netio) block from lines 274 to 291 that you need. It would be ideal if you could move this code to PopulationUtil so that you wouldn't be duplicating it.

Note that after all of these changes, your batch file will need to set some parameters to true: 
saveAllChampions
logTWEANNData
logMutationAndLineage

**Comment by leg2015** [comment]
Made an attempt at this issue. Added everything you mentioned to add, also had to extend network task in the picbreeder task because I was getting a class cast exception error. Picbreeder still runs just fine and outputs the required files. However, can't seem to get the post best objective watch file to run but hopefully it's just a small problem on my part.

**Comment by schrum2** [comment]
I think post best objective watch only applies for LonerTasks, but
Picbreeder is not a LonerTask. I'm hoping the existing lineage tracing
tools don't depend on using the LonerTask, but we can fix it if it does.

**Comment by schrum2** [comment]
Some observations on this.

In retrospect, I don't think the SelectiveBreedingEA needs to log the score information, since all scores are 0 or 1, and are pretty boring. We also don't need to create plot files.

The size of the population (number of files) being logged is larger than what I am seeing/interacting with in the domain.

Currently, each subsequent generation is still being deleted. I'm certain there is a command line parameter that fixes this ... we just need to reference it in the batch file ... I think.

The mutation log seems fine, but the lineage log (Picbreeder-Control0_Lineage_log.txt) is missing the data that it should contain. I think that there is some code in MuLambda, or maybe even from NSGA2, that needs to be copied into SelectiveBreedingEA to get the log data we want/need.

**Comment by schrum2** [comment]
It's in NSGA2. Look for every use of EvolutionaryHistory.logLineageData. The point of these logs is to track which children were created by which parents, which can later be used by the lineage browser.

**Comment by schrum2** [comment]
Also, this has nothing to do with post best objective watch. In fact, that batch file probably won't work with this task, because it requires an instance of the LonerTask.

However, lineage browsing is something different anyway. I need to make a batch file for this.

**Comment by leg2015** [comment]
Got the lineage logging set up. Need to figure out a way to access the lineage data from the task so that can get the undo button up and running

**Comment by schrum2** [comment]
I made the standard lineage browser (using postLineage.bat) work with this commit: f9d0b21bcf7e01ddebc081a69f64a78827697285

This works, and can technically be used to see the sequence of ancestors of a given image/network. However, this addition has nothing to do with the lineage button you've designed in the interface. I think we should still find a way to use that and do cool stuff with it, so this issue should stay open. However, it should be lower priority.

Additionally: Now that all of the data is being logged, you can hopefully implement the Undo button (this one still has moderate priority). Also, I think that using the reset and undo buttons should actually delete the appropriate previously saved generations and log lines, and reset the generation value in the EA. We might need to talk about the details of this before you implement them.

**Comment by schrum2** [comment]
Check the latest commit on this (referenced above).

The only thing that is needed is a way to close the DrawingPanels (images from the lineage) without the whole program closing. I guess it might also be nice if the lineage got saved ... maybe when the lineage is displayed, a prompt can appear asking to save it. Then the naming convention would be <ID>ancestor<Step>num<#> where <ID> is the id of the net that was selected when lineage was clicked, and step is the number of steps removed from that network. The final <#> is because there may be multiple images at that level.

This is a bit confusing, so here is an example lineage (hope this displays right):

```
                   |--F <-- H
           |--C <--X
A <-- B <--X       |--E
           |--D <----G
```

A is the image that was selected when lineage was clicked (incidentally, that means this image is not displayed by the lineage). Let's say the Id of A is 25. The file names would be 
B = 25ancestor1num1 
C = 25ancestor2num1
D = 25ancestor2num2
F = 25ancestor3num1
E = 25ancestor3num2
G = 25ancestor3num3
H = 25ancestor4num1

**Comment by leg2015** [comment]
I've got the close panel function working if you hit the lineage button again. However, if you press the  button on the lineage drawing panels it kills the whole program still.. Other thing is I still haven't added save function and not sure what the protocol for if multiple buttons are clicked when lineage is called should be. Also, there  still appears to be a pesky image that's not part of the lineage that shows up on the far right o the images when lineage is called.

**Comment by leg2015** [comment]
Tried again to get save to work... Still not doing it but should be close

**Comment by schrum2** [comment]
What is left on this issue?

**Comment by leg2015** [comment]
Not sure, will close
