### ISSUE TITLE
Fix reset option in picbreeder

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#152]
Currently, uses a hardcoded network to produce new random images but then reverts to the old images from before. Need to find a way to clear all old information and reload new data #95

**Comment by schrum2** [comment]
Use MMNEAT.ea.initialPopulation

**Comment by schrum2** [comment]
MMNEAT.ea.initialPopulation returns a new population, specifically a list of genotypes. The evaluateAll method expects a list of scores, each of which contains a genotype. So, when reset is clicked, completely replace the global scores variable with a new list of scores whose genotype instances are those returned by initialPopulation. You should also make sure that each member of this population has a fitness score of 1.0 so that it will be kept into the next generation by SelectiveBreedingEA.

**Comment by leg2015** [comment]
Got it up and running, but there is a troubling issue with mu that needs to be fixed first....

**Comment by leg2015** [comment]
Got mu all figured out by adding an if check. All that needs to be fiddled with now is the generation reset, but won't worry about that in this issue
