### ISSUE TITLE
add network visibility to picbreeder task

### ISSUE THREAD

**Issue by leg2015** [schrum2/MM-NEATv2#154]
#95

**Comment by schrum2** [comment]
I think the best way to implement this without cluttering the interface is to add a single button called "Network" that shows the networks of all selected images.

**Comment by leg2015** [comment]
network is up and running!  I have it where if you click the network button, it shows all networks, not just the selected ones. But that can be fixed if need be. I think it's pretty cool the way it's set up right now though, but see what you think.

**Comment by schrum2** [comment]
I do like the way it looks now! However, I'm going to nitpick about a few bugs.
1) The networks need to be drawn smaller so that their images fit completely inside of the buttons.
2) If I click evolve when networks are being displayed, the program crashes with an exception
3) When the button to switch between networks and images is clicked, all buttons that were highlighted (blue rim) remain highlighted. However, if I click evolve, it does not progress. I suspect that these buttons are being displayed as selected, but that this is out of sync with which buttons are actually selected.
4) Is there a way to show tool-tip text with the button function whenever the mouse hovers over them? It would be a nice addition.

**Comment by leg2015** [comment]
Everything but issue 4 is fixed for the save! I'll close this issue and open another one
