### ISSUE TITLE
Confirm that all VizDoom rewards/fitness make sense

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#159]
For each domain, try to get a sense for whether the fitness/rewards actually match the way the agent behaves. This may involve using the MiscUtil method to pause the game on every step, or simply when certain types of rewards happen. If the rewards don't make sense, then change them so they do. Document the changes you make in the comments for this issue.

**Comment by Serenamidori** [comment]
PredictPosition: Shooting and misses gives the agent a score ranging -0.050 to -0.070, and the successful hit gave a 0.947. This fits the range of -1 to 1 without going too low for missing, since that will happen more often than not. These scores make a lot of sense given the domain.
TakeCover: The score given for each round is just the amount of time that the agent have been alive. This make sense given that it's a domain where you're meant to dodge enemy fire.
DeadlyCorridor: You get a visible negative score for moving backward and a visible positive score for moving forward. However, there is not score change for getting shot. The goal here is to move forward into the corridor, so this makes sense. Also, the actual score that Eclipse shows is -100 + the visible score, which also makes sense to give incentive to move forward and gain more points.
MyWayHome: The untrained agents constantly score a -.2099999 because they get stuck on a wall and cannot finish the maze before the 2100 step timeout. This makes sense given that the living reward is -0.0001, so the score is a negative score based on how long they stay in the maze.
DeathMatch: Kind of hard to tell what gives what score wise, but I can tell that the game variables are affecting it. This may be one we need to explore to figure out the rewards, but you seem to get positive scores for picking up health packs and ammo, as well as getting shot and surviving(?).
DefendCenter/DefendLine: This one makes sense given a few plays, you get a point for every enemy you kill and lose a point if you die.
HealthGather: The score is the time spend alive, and I don't think you get any bonus for picking up health packs besides just living longer. (oh my god it keeps crashing why this)
MultiDeathMatch: This domain can't actually score anything given the state (agent is alone) so it won't lose a point for dying and can't gain any score from killing. The game variables are health and ammo, so I'm guessing scoring is similar to regular DeathMatch, meaning getting shot and staying alive would yeild a positive score and staying alive with no shots taken would not (?)

So far, I don't fully understand the DeathMatch or MultiDeathMatch scoring systems, but they generally make sense when you see the match take place and see the score given. I don't think any need to be changed at the moment, the only ones would be these two if we choose to pursue them any time soon.
