### ISSUE TITLE
VizDoom variable screen regions and sample sizes

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#164]
We need even more options for how to grab vizdoom input. Here is a list:

doomInputStartX: x-coord where input region starts
doomInputStartY: y-coord where input region starts
doomInputHeight: height of input region
doomInputWidth: width of input region

These four parameters will give us ultimate flexibility over the region of the screen that gets used as input to the agent. Once all of this is implemented, it can even replace your existing row and screen input functions, since those are just special cases of this general scheme.

After the above works, the next step is to reduce the sample rate. Make the following parameters:

doomInputPixelSmudge: the size of screen regions that get smudged together into one.

If doomInputPixelSmudge is 3, then it means that you break up the input region into 3X3 blocks, and each block creates a single network input. The value of the input should be the average across all numbers in the 3X3 block. If the size of the overall region ends up not being divisible by the smudge parameter, then just don't include pixels outside of the region in the average calculation.

**Comment by Serenamidori** [comment]
Added those parameters, as well as a fifth "doomInputColorVal" that takes in an int for the color you want. I have checks in place that 0, 1, and 2 map to blue, green, and red respectively, 3 allows all colors to be used, and any other number will not be accepted and defaults back to 2 (red). I chose red because it won't accidentally make the inputs too large by using all colors, and red seems to have the move dramatic contrast (from what I see)

And now we have a method in VizDoomTask called getInputs that takes in the GameState, x, y, width, height, and color of the selection we want to use for our inputs. This can all be altered in the command line as well. So far i'm only testing with Basic Shoot Task before editing any of the other tasks.

**Comment by Serenamidori** [comment]
Added doomInputPixelSmudge as a parameter and worked it into the checks of the specific task files. We also split up the smudge and inputs methods to allow for multiple colors, but to set them as red then green then blue (as in the whole section and not pixel by pixel) 

We still need to test all the inputs, especially so for smudging, and this can either be done through from print statements or actual JUnit testing with a small visual to work off of. For now, this is all implemented.
