### ISSUE TITLE
Test the new Inputs and Smudge methods for VizDoom

### ISSUE THREAD

**Issue by Serenamidori** [schrum2/MM-NEATv2#166]
Do this by JUnit testing with a small test visual and with print statements in VizDoomTask

**Comment by Serenamidori** [comment]
I started to do a non-JUnit test using print statements and some old Tetris paper. I've tested that larger (and not perfectly divisble) portions can be smudged correctly, and tomorrow I'll be testing the actual averaged values (if you deem that necessary)

**Comment by schrum2** [comment]
Since the smudge function takes a double array as input, no interaction
with the VizDoom game screen is actually needed. Therefore, I think it
wouldn't be too difficult to do some unit tests of this function, including
some checking of the exact average values calculated ... at least for a few
fairly small examples. So, please make these tests.

**Comment by Serenamidori** [comment]
Added JUnit tests to check for correct smudged values, sizes, and positions. 6fc6170ec3cc81d907eee7b84677364788394591
