### ISSUE TITLE
Generalize TorusPredPreyTask

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#17]
TorusPredPreyTask currently evolves one prey against a team of predators using a fixed policy.

This issue involves either generalizing this task, or creating several other tasks that accomplish the necessary goals (but avoid duplicating code). There should be a way to evolve not just against one prey, but against a team of prey agents. There should also be a way to have the prey use a fixed policy, but evolve the predators.

More complex options are possible, but are in a different issue.

**Comment by Rollinsa** [comment]
Completed the TorusEvolvedPreyVsStaticPredatorsTask (this was renamed from the "TorusPredPreyTask"). I added a command line parameter so that the number of preys can be specified, then I added the code necessary to evolve that number of preys. Next I will make and complete a TorusEvolvedPredatorsVsStaticPreysTask with static preys and evolved predators, and after that I will do a class that evolves both (coevolution) in another issue that you assigned me.

**Comment by Rollinsa** [comment]
Completed TorusEvolvedPredatorVsStaticPreyTask so that predators are evolved (as many as specified in parameters) and the prey are static. The user specifies which of the agents (the prey or the predators) get evolved by specifying which task will be used. I then created a super/parent class called "TorusPredPreyTask" which contained most of the code in the two specific children classes (extended by the two specific evolving prey or predator classes) so that I was then able to delete almost all of the code in the children, leaving only a specification to the parent class of which type of agent is being evolved and methods providing a list of the prey and predator controllers (one is static and the other is evolved according to parameter specifications).
