### ISSUE TITLE
Different RL Glue port numbers for batch files

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#184]
That rlGlue parameter specifies which port an RL Glue domain will use to communicate with the RL Glue program. A consequence of this is that if you want to run multiple RL Glue experiments at the same time, each one must be using a different port number.

The default port number is 4096, and any port number used should generally be larger than this to assure it isn't being used by something else.

Since each port number needs to be different, we won't be able to use the asynchronous launch multiple batch file with RL Glue tasks unless we modify the RL Glue batch files.

The following would be ideal:
If the runNumber is 0, then the rlGluePort should be 4096.
If the runNumber is 1, then the rlGluePort should be 4097.
If the runNumber is 2, then the rlGluePort should be 4098.
etc.

Essentially, if the runNumber is x, the rlGluePort should be 4096+x

Doing this will require the arithmetic option of the batch file set command. Modify the batch files for all RL Glue experiments so that they set the rlGluePort to be 4096 + the run number.

If you have any confusion about how the port number works, ask Gabby.

**Comment by Rollinsa** [comment]
Changed the RLGlue batch files so that each experiment that is run will be run on the rlGluePort 4096+the run number. Note: if different experiment types of the rlGlue are run simultaneously, this won't work currently (still) because the port numbers will conflict. The solution might be to start each port number at ten more in each batch file, so that each batch file is allowed a gap of 10 ports (for instance, the first could be 4096+run number, the next would be 5006+run number, and so on) given that we have enough port numbers to support this. Also updated the comments in the launchMultiple batch files so that they represent a batch file that actually exists.
