### ISSUE TITLE
VizDoom sensorLabels

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#201]
The last time we did a post watch on VizDoom experiments, the monitorInputs option made the code crash. Double check this and figure out why. Specifically, verify that the sensorLabels work correctly when using smudged inputs.

**Comment by Serenamidori** [comment]
Looking into this- so far the sensor labels do work with the basic shooter task when it's smudged. My hunch is that the other tasks are missing something, since I had to do batch changes to all tasks at once, I might have left something out. We're testing smudge with DefendCenter now, and I'll update from there

**Comment by Serenamidori** [comment]
Tested DefendCenter, and the inputs and outputs work, so it must have been a server side issue
