### ISSUE TITLE
Mario input frame

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#203]
Have parameters that specify the width and height of the mario input frame. We want to be able to sense more than a 3by3 grid around mario.

We also need to know exactly what the probe function is returning ... does it only sense walls? What about enemies? Do we want a separate group of inputs for different classes of objects in the world?

**Comment by Serenamidori** [comment]
We now have 4 parameters, marioInputWidth, marioInputHeight, marioInputStartX, and marioInputStartY. These parameters will decide how big the input frame is, and where the center (0, 0) will be located. Instead of the single created of the inputs array, we created it of the correct size according to the height and width, and then loop through and x and y coordinates, adding the bias last. This way, we will always start at the bottom left corner and we can measure the center to be where we want it by the offset starts.

As for the questions, I'm not sure yet and I'm not sure we'll have a dedicated way to test that given the NN are random. I won't close this issue until we decide what to do there, but it shouldn't be a problem :+1:

**Comment by Serenamidori** [comment]
Closing this now, because we have two input frames, one for the world and one for the enemies
