### ISSUE TITLE
Post-Watch any generation from coevolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#211]
It seems that for competitive coevolution, it will be very important to watch the behavior of individuals at every point in evolution ... when the fitness suddenly changes in a weird way, we might want to see the behavior of the agents.

It is already possible to save all of the champions from each generation by using the saveAllChampions option, and it is possible to save ALL networks from evolution by setting cleanOldNetworks to false.

What we need now is an easy way to watch individuals from any generation of coevolution.  I think it might already be possible to do this by using your ObjectiveBestTeamsExperiment. For example, if you save all of the champions, then you can simply specify filenames from earlier champions as coevolvedNet1, coevolvedNet2, etc. (these expect the whole filename after all). For ever, if I don't want to specify the exact team, and instead simply want to look at the best from a particular generation, I think you can do it by making the lastSavedGeneration parameter be a generation BEFORE the last one. However, you will need to make a special batch file for this.

So, this "issue" basically requires you to confirm all of these ideas, and then make that one new batch file (the generation will be a parameter for the batch file).

**Comment by Rollinsa** [comment]
Tested the ability to test specified teams from specified generations based on providing the team member (xml files). Updated competitive coevolution batch files to save all champions by default so that any generation's best agents can be evaluated and watched at the end. Created new batch file for coevolution which allows the user to specify which generation they would like to view and then evaluates/watches all possible combinations of the champions from that generation (just like postBestObjectiveEval(or Watch)Cooperative, except for a specified generation). Updated all postBestObjectiveEval batch files to set watchLastBestOfTeams to true.
