### ISSUE TITLE
Scent/color paths in predator prey

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#232]
It would be nice if we could visualize in the pred/prey world when the agents are using different modules. Even if they all only have one module, it could be useful to see the paths they are traversing.

It should essentially look like the similar feature in Ms. Pac-Man: http://nn.cs.utexas.edu/?ol-pm

**Comment by schrum2** [comment]
This feature is actually important now. It is essential that we implement it in order to analyze how your 2M results use their modules.

You should be able to turn the setting on/off with a command line parameter. The paths should only apply to evolved agents, and not the static prey. For agents controlled by a network, the TWEANN has a method that returns the module number that was used most recently. In one of the util classes there is a static method that will convert an int to a unique Color.

Have a 2D array of colors that indicates the color of each grid cell. The default is white. On each time step, evolved agents change the color of their cell to match the module they used. 

Also, sweep through all cells on each time step to make the existing color fade closer toward white.

**Comment by Rollinsa** [comment]
Implemented the parameter "viewModePreference" so that the scent paths will only happen when that parameter is on. Seems to work fine still. Now need to make it based off the modules rather than agent type, and need to implement it for the prey eventually

**Comment by Rollinsa** [comment]
This is mostly fixed, but there is a bit more to do eventually (but should work completely for the current experiments). The code still needs to be implemented for the prey to work with viewing the mode preference (it was only implemented to work for when predators are being evolved), and the code also needs to be generalized to look at all of the predators' module usage and number of modules rather than just the first predator's (will not work if the predators have different numbers of modules than each other because it assumes that each predator has the same number of modules).

**Comment by schrum2** [comment]
Can this issue be closed? Does any code still need to be committed?
