### ISSUE TITLE
Create save feature for Breedesizer

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#310]
Ned to figure out how to save the wave files you create so you can properly override the save method for breedesizer.

**Comment by schrum2** [comment]
Dedicate some time to messing around with this again. However, as before, set a time limit in advance and move on to something else if you get stuck.

**Comment by twerisa** [comment]
Potentially useful links for this task: 
http://www.developer.com/java/other/article.php/2226701/Java-Sound-Creating-Playing-and-Saving-Synthetic-Sounds.htm
https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/spi/FormatConversionProvider.html

**Comment by twerisa** [comment]
This issue is solved, but I noticed something strange when looking at BreedesizerTask. The AudioFormat initialized in BreedesizerTask conflicts directly with the AudioFormat used to save files from a CPPN. From my reading on WAV files, I found that there were two main initialization options when choosing AudioFormats - one is 16 bit, 44100 default sample rate, and signed, and the other is 8 bit with 11025 as a default sample rate, and it is unsigned. The conflict between the initializations raises concerns for me, but the files are actually successfully saving and playing for the first time so I'll leave it as it is for now.
