### ISSUE TITLE
BoardGameFeatureExtractor

### ISSUE THREAD

**Issue by DarwinJohnson** [schrum2/MM-NEATv2#322]
Create a BoardGameFeatureExctractor Interface in which T extend Network is true. This wil be used to extract the features from a BoardGameState.  This will provide several ways to represent the features.

**Comment by schrum2** [comment]
Correction: BoardGameFeatureExctractor should not have a T extends Network.
Rather, it should have a T extends BoardGameState.

The main function of BoardGameFeatureExctractor is getFeatures that takes in a T (something that extends BoardGameState) and returns a double array.

In fact, the getDescriptor method that we worked on recently is sort of a default feature extractor. You can actually define a class called RawFeatureExtractor that simply returns the result of the getDescriptor call.

You can also make a SplitPiecesFeatureExtractor that returns double the number of values as there are squares on the board. With this extractor, instead of returning one array worth of board spaces that have different symbols for different types of pieces, you return two board's worth of values: the first set identifies pieces of one type and ignores the other, while the second set only identifies pieces of the other player.

**Comment by schrum2** [comment]
The getFeatureLabels method of BoardGame should be removed, and instead be made into a method of the BoardGameFeatureExtractor (note: all feature extractor classes should be in their own sub-package). Change the class RawBoardGameFeatureExtractor into Raw2DBoardGameFeatureExtractor and make it apply only to 2D board game states. Then move the getFeatureLabels method definition from TwoDimensionalBoardGame into the new Raw2DBoardGameFeatureExtractor class.

You will also need to change the static and coevolution tasks to get their feature labels from the feature extractor being used instead of the board game. Before you can do this, there will need to be a command line class parameter that defines the featureExtractor used by evolved board game agents. An instance of this class should be instantiated in the constructor for the NNBoardGameHeuristic, because the feature extractor will live inside of this class. Instead of directly sending the results of getDescriptor into the neural network, you will need to get NN inputs from the getFeatures call of the feature extractor.

**Comment by DarwinJohnson** [comment]
Are there any more Feature Extractors that need to be implemented soon?

**Comment by schrum2** [comment]
Nope, I'm closing this issue. If we think of a new feature extractor we need, I'll make a new issue for it.
