### ISSUE TITLE
MIDI playback with CPPN

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#330]
As I understand it (and this may be overly simplified), a MIDI file is basically a collection of notes, and can therefore be played back in different ways (different instruments for example). Develop a way to play a MIDI file with an evolved CPPN as the "instrument." Then, we could play back entire songs with our evolved CPPNs.

**Comment by twerisa** [comment]
https://www.cs.cmu.edu/~music/cmsip/readings/MIDI%20tutorial%20for%20programmers.html
Useful webpage about how MIDI files work

**Comment by schrum2** [comment]
Even if all you have working is a rudimentary version of this, I would like to plug it into Breedesizer. Add a button that plays a MIDI file (specified by a command line parameter in Parameters.java) using the currently selected CPPN sound. (Look at the PlayOriginal button in RemixBreeder to see how to add such a button)

**Comment by twerisa** [comment]
Some useful info about MIDI tracks:
-getCommand() specifies whether note is ON or OFF
-getData1() is the key (int that encodes note and octave)
-getData2() is the velocity (has to do with volume)
*NOTE_ON with velocity == 0 is the same as NOTE_OFF*

From what I've seen about MIDI tracks, there is no way to directly access the duration of a note. The pieces of data above are the main things that are easily accessible from MIDI tracks. The way to calculate the duration is to find the time where the note starts and the time where the note stops (often uses NOTE_ON with a velocity of 0 rather than NOTE_OFF) and calculate the difference between the two. I'm not sure where to access the time that each track starts.

**Comment by twerisa** [comment]
Links about conversion between ticks and milliseconds:
http://www.harmoniccycle.com/hc/music-25-MIDI-BPM-PPQ.htm
https://stackoverflow.com/questions/2038313/midi-ticks-to-actual-playback-seconds-midi-music

**Comment by twerisa** [comment]
A possible solution to the CPPN playback only being able to play one note at once could be creating another SourceDataLine (?) so that there can be multiple buffers running, and therefore multiple voices playing. Might involve some more significant code restructuring. Next week, get MIDI functioning for multiple voices and generalize code so that BPM and PPQ can be accessed generally from any MIDI file.

**Comment by schrum2** [comment]
I think to make this work, we need to have the ability to play back multiple sounds simultaneously.

First, make an inner class within PlayDoubleArray that encapsulates the static line, lineSave, buffer, bufferSize, playing, and available variables. The static methods that depend on these variables should also be encapsulated within the new class, which should be called AmplitudeArrayPlayer (should extend Thread). Compare with the CPPNNoteSequencePlayer in MIDIUtil. Note that there should still be a static method for launching sound playback, but the method should return the AmplitudeArrayPlayer, providing a means of stopping the sound.

Once the AmplitudeArrayPlayer exists, create an example in SoundUtilExamples that tries to play two sounds simultaneously on different SourceDataLines. If this works, then we will finally be able to play chords and other simultaneous notes in the MIDI player. More on this in my next post.

**Comment by schrum2** [comment]
Once we have a way to play back multiple sounds simultaneously, then I think we can play back a MIDI file accurately by doing the following:

I read somewhere that the standard number of sound channels for a MIDI track is 16 (there can be more, but this is a good place for us to start). For MIDI playback, we can create up to 16 arrays of frequency values. The lengths of the arrays will equal the number of ticks in the track. Sections of the array with 0 play no notes.

Playing back this group of arrays properly will be tricky, since it will involve multiple AmplitudeArrayPlayers. I'm also not sure what the best way to synchronize all of the playback is, but we'll deal with that problem once we get to this point.

**Comment by schrum2** [comment]
This is still a rough issue. We know that several notes can be played simultaneously now, but we need to figure out how to make various notes play at the right times.

One util method that I think could help would be a way to get the number of ticks in a track:
public static int ticksInTrack(Track track) would loop through the track size and calculate the maximum getTick() result across all ShortMessage events.

Then, see if you can create a method that returns an array of arrays (a 2D array) in which each sub-array represents a different channel (on which sound can be played simultaneously) and the numeric values in the individual channel arrays represent the frequencies of the notes played by the MIDI file during the given range of ticks (each sub array has a length derived from the ticksInTrack method).

**Comment by schrum2** [comment]
Fix speaker pop according to this:
https://stackoverflow.com/questions/33453489/popping-sound-with-sourcedataline-audio

**Comment by schrum2** [comment]
Before trying to play back multiple separate sounds simultaneously, do some research into the properties of sound waves. I think there might be a way to take two separate sound waves and combine them into a single sound wave that sounds the same as both waves playing separately.

However, if a way to do this exists, I can confirm that it is NOT as simple as adding up the amplitude values across all the waves. I think the reason for this has to do with constructive and/or destructive interference.

Look into it a little bit and let me know what you find. If nothing works out, then we'll need to simply synchronize the separate sound lines.

**Comment by twerisa** [comment]
This [link](https://stackoverflow.com/questions/12568326/merge-two-audio-filesnot-concat-in-javaapi) has links to some useful information about merging two sounds in java. The information I have found mostly applies to WAV files, but I'm thinking that once a MIDI file is converted to an array, it may be able to be converted into a WAV file and analyzed using WAV file utility methods. However, if this isn't possible, then this info is irrelevant to the issue. I've also found info about overlapping two files into a singular file, but this wouldn't work for MIDI sound synthesis because everything is coming from a singular file and is written into multiple channels

**Comment by schrum2** [comment]
The numerous pieces of advice on the internet, combined with my own initial expectation of how adding waves should work, has convinced me that adding the waves together is in fact the correct way to do it. However, it is clear that play back of fur Elise still sounds weird in a few places with this method. I think that we should look for the causes of this error in other places, and strive to make MIDI playback of different MIDI files work. I will be making some commits soon associated with this issue that point out places to look for errors.

**Comment by schrum2** [comment]
I've taken care of the major data structure issues associated with this. However, you still need to move the code into the CPPN note sequence player, make breedesizer actually use it, delete the old code that isn't used, comment the code, and tie up most loose ends.

Once the CPPN note player is back in shape, it should be easier to add back the ability to interrupt play.

We also need to figure out why dividing by 2 is a magic number, and see if this approach can work with other MIDI players.

**Comment by twerisa** [comment]
I've found some interesting discrepancies with tempo playback when testing out another solo piano audio file. I measured tempo markings using a metronome on my phone to see if there was a common pattern with a difference in playback speed, but this is what I found:
Original Fur Elise: 140-145 BPM
Deconstructed Fur Elise: 110 BPM
Original Solo Piano: 145 BPM, 95 in development
Deconstructed Solo Piano: 192 BPM, 151 in development
It is interesting to me that playback speeds up in some cases and slows down in others. I adjusted the magic number 2 by increasing and decreasing it, but it didn't seem to affect the solo piano playback in any way.

**Comment by schrum2** [comment]
In theory, that magic number 2 should only affect volume, which in some
cases also affects speaker pop/crackle. However, we will have to keep
trying different things to see what works.

**Comment by schrum2** [comment]
I think the only items on the TODO list for this issue are to calculate the note length multiplier more accurately, and to figure out a general way to account for what we divide the sum of amplitudes by to get a good volume. Try doing a bit more research on the note length issue, and I'll look at the volume issue.
