### ISSUE TITLE
Show networks for single population coevolution

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#368]
There are several command line parameters responsible for displaying network information in the post watch batch files. Things like showNetworks, showCPPN, monitorSubstrate, monitorInputs, showWeights, etc.

The reason that all of the interesting network and input information displays when these parameters are set is that the LonerTask sets up all of the visualization before the evaluation happens. Look at the call method inside of the EvaluationThread inner class of the LonerTask.

Generalize this code by creating a static method in a new util class called CommonTaskUtil in the edu.utexas.cs.nn.tasks package. This static method should take a  genotype and return a Pair of DrawingPanels: one for the TWEANN, and one for the CPPN, either or both of which could be null. This new method will replace some code in LonerTask.

Then you can also call this method in the SinglePopulationCoevolutionTask. In this task, control networks and CPPNs need to be displayed for all genotypes in the group before the evaluateGroup method is called, and after the evaluation all DrawingPanels need to be cleaned up.

Take this task in steps. Generalize the code for LonerTask by extracting the static util method first, and commit that. Once that works with visualization and post evals, move on to showing networks during coevolution.

**Comment by DarwinJohnson** [comment]
It's now possible to watch both StaticOpponent and Coevolution Batch Files during evolution, and it's still possible to run a PostWatch on a StaticOpponent. It's still not possible to run a PostWatch on a Coevolution Batch File, but that task is part of Issue #369.
   When watching a Coevolution Batch File during evolution, the Board Inputs remain the same for both Players (because they're both playing on the same Board), and the Processing Panel switches between Players after one Player makes a Move.
