### ISSUE TITLE
board game "other" score that tracks win/loss/tie

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#375]
The standard win/loss/tie fitness function contains useful information that we would like to have, even if we are evolving with an alternative fitness function, such as the advanced Checkers fitness function. The fitness score may be high, but are we winning?

In order to tell, you need to track the win/loss/tie fitness as an "other" score. To make things easy, track this value as an other score, regardless of what fitness function is being used for the sake of selection.

**Comment by DarwinJohnson** [comment]
The tracking of Other Scores now works for BoardGames. However, the SimpleWinLoseDrawBoardGameFitness Score does not appear when the Checkers Advanced Fitness is the primary Fitness Score. The Plot Window will state that it's depicting the Other Score, but nothing will appear in the graph. This is likely due to the scaling of the window, but I am unsure of how to fix this issue. Once this is done, however, this Issue can be closed.

**Comment by schrum2** [comment]
It's possible that you are either not "registering" the "other" score in the constructor for the task, or that the number of other scores (a method defined in the task) is returning the wrong number. Also note that when you register an "other" score, extra parameters are required to specify that it is an "other" score rather than a fitness objective. Alice has some experience with this, so ask for her help.

**Comment by DarwinJohnson** [comment]
The Other Scores are finally properly tracked in BoardGameTasks. The Other Scores are plotted as expected, and everything is working.
