### ISSUE TITLE
Comment and remove compiler warnings from RL Glue code

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#40]
This is code in the edu.utexas.cs.nn.tasks.rlglue package.

**Comment by schrum2** [comment]
Not all compiler warnings need to be fixed, but see what you can do.

This issue should actually extend to all code associated with RL Glue, including the other domains: cart pole, puddle, etc.

**Comment by Serenamidori** [comment]
Commented, cleaned up, and removed warnings from the files you wanted me to go through. Here's a more detailed list, including the files I had to leave warnings in and which files I skipped to fix up with Lauren later.

RLGlueTask.java - There are 3 warnings, but fixing one will create errors for the others. It refers to public static RLGlueAgent agent, where it wants to be public static RLGlueAgent<?> agent.
CartPoleViewer.java- Removed unused import
BertsekasTsitsiklisTetrisExtractor.java - I did remove a commented-out blotMobilePiece call because my comments said it messed with the afterstate scores. I removed it, since it did not seem necessary, but best to make note of the change here.
ExtendedBertsekasTsitsiklisTetrisExtractor.java - Same thing as BertsekasTsitsiklisTetrisExtractor, took out the blotMobilePiece call that was commented out 
BertsekasTsitsiklisTetrisExtractorTests.java - Removed unused imports
ExtendedBertsekasTsitsiklisTetrisExtractorTests.java - Removed unused import
ModelFreeTetrisExtractor.java - Same thing as BertsekasTsitsiklisTetrisExtractor, took out the blotMobilePiece call that was commented out
PuddleWorldViewer.java - Removed unused import
TetrisAfterStateAgentTests.java - Removed unused import
TetrisAfterStateGeneratorTests.java - Removed unused imports and commented-out print statements
TetrisViewer.java - 1 warning is still here because of "dead code," but you said to leave it because od debugging purposes.

Skipped so far:
    HyperNEATTetrisTask.java, HyperNEATTetrisExtractor.java,
