### ISSUE TITLE
Create a FleeNearest prey controller

### ISSUE THREAD

**Issue by schrum2** [schrum2/MM-NEATv2#51]
Create a new controller for prey agents that flees the nearest predator instead of maximizing distance from all. You will also need to create a command line parameter that specifies the Java class to use for defining static prey agents.

**Comment by Rollinsa** [comment]
Created PreyFleeClosestPredatorController, but it still is not being used anywhere. I still need to create a command line parameter that allows a user to switch between using the "PreyFleeAllPredators" controller and the new "PreyFleeClosestPredator" controller as the static prey agents when predators are evolved instead of just always using the PreyFleeAllPredators controller by default.

**Comment by Rollinsa** [comment]
I finished with the command line parameter that allows a user to switch between static preys for when predators are being evolved
